name: Deploy

on:
  push:
    branches: [ gh-actions ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Setup Neko
        run: |
          sudo add-apt-repository ppa:haxe/snapshots -y
          sudo apt-get update -qqy
          sudo apt-get install -qqy neko

      - name: Setup Haxe
        run: |
          set -ex
          mkdir ./linuxBinaries
          curl -sSL https://build.haxe.org/builds/haxe/linux64/haxe_latest.tar.gz -o ./linuxBinaries/haxe_bin.tar.gz
          tar -xf linuxBinaries/haxe_bin.tar.gz -C linuxBinaries --strip-components=1
          sudo mkdir -p /usr/local/bin/
          sudo mkdir -p /usr/local/share/haxe/
          sudo ln -s `pwd`/linuxBinaries/haxe /usr/local/bin/haxe
          sudo ln -s `pwd`/linuxBinaries/haxelib /usr/local/bin/haxelib
          sudo ln -s `pwd`/linuxBinaries/std /usr/local/share/haxe/std

      - name: Prepare dependencies
        run: |
          git config --global gc.auto 0 # we will call gc manually during deploy
          haxelib newrepo
          haxelib install all --always
          haxelib dev hxparse libs/hxparse
          haxelib dev hxtemplo libs/hxtemplo
          haxelib dev hxargs libs/hxargs
          haxelib dev markdown libs/haxe-markdown
          haxelib dev dox libs/dox
          git clone --depth=1 https://github.com/HaxeFoundation/hxcpp.git
          cd hxcpp/tools/hxcpp
          haxe compile.hxml
          cd ../../../
          haxelib dev hxcpp hxcpp
          haxelib list

      - name: Generate and validate docs
        run: |
          haxe gen.hxml
          neko Gen.n
          # validate html
          wget -q https://github.com/validator/validator/releases/download/18.8.29/vnu.jar_18.8.29.zip
          unzip vnu.jar_18.8.29.zip
          java -jar dist/vnu.jar --errors-only html/*.html # only for the top level html for now since there are many errors in e.g. js/html/*.html
